language: python
python:
    - "2.7"
    - "2.6"

sudo: false

install:
    - pip install "Sphinx==1.3b1"   # autotest requires Sphinx during install
    - pip install -r requirements-travis.txt
    - git clone https://github.com/avocado-framework/avocado.git avocado-libs
    - cd avocado-libs
    - pip install -r requirements-travis.txt
    - python setup.py install
    - cd ..
    - rm -rf avocado-libs

script:
    - make check
