language: python
python:
    - "2.7"

branches:
    only:
        - master

virtualenv:
    system_site_packages: true

before_script:
    - echo "deb http://ppa.launchpad.net/lmr/autotest/ubuntu saucy main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -q
    - sudo apt-get -y --force-yes install autotest

install:
    - pip install sphinx tox simplejson MySQL-python
    - pip install -r requirements.txt

script:
    VIRT_TEST_DIR=. ./tools/run_unittests_nose.py -c .nose.cfg -s virttest --virttest-skip-tests "versionable_class_unittest"
