language: python
python:
    - "2.7"

branches:
    only:
        - master

install:
    - pip install sphinx tox simplejson MySQL-python
    - pip install -r requirements.txt --use-mirrors

script:
    VIRT_TEST_DIR=. ./utils/unittest_suite_nose.py -c .nose.cfg
