language: python
python:
    - "2.7"
    - "2.6"

sudo: false

install:
    - pip install Sphinx==1.3b1
    - pip install -r requirements-travis.txt
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then AVOCADO_BRANCH=36lts; else AVOCADO_BRANCH=master; fi; git clone --depth 1 --branch $AVOCADO_BRANCH https://github.com/avocado-framework/avocado.git avocado-libs    # avocado-46+ does not supports python-2.6
    - cd avocado-libs
    - pip install -e .
    - cd ..
    - pip install -e .

script:
    # Create some fake binaries to make vt-bootstrap happy
    - mkdir -p /tmp/dummy_bin
    - touch /tmp/dummy_bin/arping
    - touch /tmp/dummy_bin/tcpdump
    - chmod 777 /tmp/dummy_bin/*
    - export PATH="/tmp/dummy_bin:$PATH"
    # Setup Avocado-vt for functional tests
    - AVOCADO_LOG_DEBUG=yes avocado vt-bootstrap --vt-skip-verify-download-assets --yes-to-all
    # Run tests
    - inspekt checkall --disable-lint W,R,C,E1002,E1101,E1103,E1120,F0401,I0011,E1003 --exclude avocado-libs --no-license-check
    # Cleanup avocado libs
    - rm -rf avocado-libs
