language: python
python:
    - "2.7"

branches:
    only:
        - master

before_script:
    - echo "deb http://ppa.launchpad.net/lmr/autotest/ubuntu saucy main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -q
    - sudo apt-get install autotest

install:
    - pip install sphinx tox simplejson MySQL-python
    - pip install -r requirements.txt

script:
    VIRT_TEST_DIR=. ./tools/run_unittests_nose.py -c .nose.cfg -s virttest
